(function(){
const GA_MEASUREMENT_ID='G-2JWTMR6FBL';
window.dataLayer=window.dataLayer||[];
window.gtag=window.gtag||function(){window.dataLayer.push(arguments);};
window.gtag('js',new Date());
window.gtag('config',GA_MEASUREMENT_ID,{send_page_view:true});
if(!document.querySelector(`script[src*="googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}"]`)){
  const gaScript=document.createElement('script');gaScript.async=true;gaScript.src=`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`;document.head.appendChild(gaScript);
}
document.addEventListener('click',function(event){const link=event.target.closest('a[href]');if(!link)return;let url;try{url=new URL(link.href,location.href);}catch(_){return;}const isAmazon=url.hostname==='amzn.to'||url.hostname.endsWith('.amazon.com')||url.hostname==='amazon.com'||url.hostname==='link.amazon';if(!isAmazon)return;window.gtag('event','amazon_outbound_click',{link_url:url.href,link_text:(link.textContent||'').trim().slice(0,120),page_location:location.href});});
const products=window.STYLE_AMAZON_PRODUCTS||[];
const labels={fashion:'Fashion',tops:'Tops',sweaters:'Sweaters',jackets:'Jackets',pants:'Pants',jeans:'Jeans',shoes:'Shoes',bags:'Bags',jewelry:'Jewelry',accessories:'Accessories',beauty:'Beauty',skincare:'Skincare',fragrance:'Fragrance',fall:'Fall Style'};
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/\"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function primaryLabel(p){return labels[p.categories[0]]||'Style Find'}
function card(p){return `<article class="product-card"><a class="product-image-wrap" href="${p.link}" target="_blank" rel="sponsored nofollow noopener"><img class="product-image" src="${p.image}" alt="${esc(p.title)}" title="${esc(p.title)}" loading="lazy" decoding="async" onerror="this.style.display='none';this.parentElement.classList.add('image-missing')"></a><div class="product-copy"><span class="product-kicker">${esc(primaryLabel(p))}</span><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><a class="shop-button" href="${p.link}" target="_blank" rel="sponsored nofollow noopener">Shop on Amazon <span class="paid-link">(paid link)</span><span aria-hidden="true">↗</span></a></div></article>`}
function renderHero(){const el=document.getElementById('heroShowcase');if(!el)return;const ids=[1,10,13];const chosen=ids.map(id=>products.find(p=>p.id===id)).filter(Boolean);if(chosen.length<3)return;el.innerHTML=`<a class="hero-product hero-main" href="${chosen[0].link}" target="_blank" rel="sponsored nofollow noopener"><img src="${chosen[0].image}" alt="${esc(chosen[0].title)}"><span>FALL EDIT</span><strong>${esc(chosen[0].title)}</strong></a><a class="hero-product hero-small one" href="${chosen[1].link}" target="_blank" rel="sponsored nofollow noopener"><img src="${chosen[1].image}" alt="${esc(chosen[1].title)}"><span>COZY LAYERS</span></a><a class="hero-product hero-small two" href="${chosen[2].link}" target="_blank" rel="sponsored nofollow noopener"><img src="${chosen[2].image}" alt="${esc(chosen[2].title)}"><span>ACCESSORIES</span></a>`;}
function renderFeatured(){const el=document.getElementById('featuredProducts');if(!el)return;const ids=[1,10,13,2,12,15];el.innerHTML=ids.map(id=>products.find(p=>p.id===id)).filter(Boolean).map(card).join('');}
function renderStory(){const el=document.getElementById('storyProducts');if(!el)return;const ids=[16,17,5];el.innerHTML=ids.map(id=>products.find(p=>p.id===id)).filter(Boolean).map(p=>`<a class="story-product" href="${p.link}" target="_blank" rel="sponsored nofollow noopener"><div><img src="${p.image}" alt="${esc(p.title)}"></div><span>${esc(primaryLabel(p))}</span><strong>${esc(p.title)}</strong></a>`).join('');}
function renderCategory(){const el=document.getElementById('categoryProducts');if(!el)return;const params=new URLSearchParams(location.search);const category=params.get('category')||'fashion';const chosen=products.filter(p=>p.categories.includes(category));const label=labels[category]||category;const description=`Curated ${String(label).toLowerCase()} finds chosen for elevated, wearable and save-worthy style.`;document.getElementById('categoryEyebrow').textContent='STYLE AMAZON FINDS / '+label.toUpperCase();document.getElementById('categoryTitle').textContent=label+' Finds';document.getElementById('categoryIntro').textContent=description;document.title=`${label} Finds | Style Amazon Finds`;el.innerHTML=chosen.length?chosen.map(card).join(''):'<p>More finds are being added to this edit.</p>';}
function renderAll(){const el=document.getElementById('allProducts');if(el)el.innerHTML=products.map(card).join('');}
renderHero();renderFeatured();renderStory();renderCategory();renderAll();
})();