(function(){
const products=window.ROOMWORTHY_PRODUCTS||[];
const labels={bedroom:'Bedroom',kitchen:'Kitchen',bathroom:'Bathroom',organization:'Organization','renter-friendly':'Renter-Friendly','small-spaces':'Small Spaces',lighting:'Lighting',entryway:'Entryway',decor:'Decor'};
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function card(p){return `<article class="product-card"><a class="product-image-wrap" href="${p.link}" target="_blank" rel="sponsored nofollow noopener"><img class="product-image" src="${p.image}" alt="${esc(p.title)}" loading="lazy" onerror="this.style.display='none';this.parentElement.classList.add('image-missing')"></a><div class="product-copy"><span class="product-kicker">ROOMWORTHY PICK</span><h3>${p.title}</h3><p>${p.description}</p><a class="shop-button" href="${p.link}" target="_blank" rel="sponsored nofollow noopener">View on Amazon <span class="paid-link">(paid link)</span><span aria-hidden="true">↗</span></a></div></article>`}
function renderFeatured(){const el=document.getElementById('featuredProducts');if(!el)return;const ids=[1,5,8,10,17,18,20,23];el.innerHTML=ids.map(id=>products.find(p=>p.id===id)).filter(Boolean).map(card).join('');}
function renderCategory(){const el=document.getElementById('categoryProducts');if(!el)return;const params=new URLSearchParams(location.search);const room=params.get('room')||'organization';const chosen=products.filter(p=>p.categories.includes(room));const label=labels[room]||room;document.getElementById('categoryEyebrow').textContent=label.toUpperCase();document.getElementById('categoryTitle').textContent=label;document.getElementById('categoryIntro').textContent=`Curated ${String(label).toLowerCase()} finds for apartments, small spaces and everyday living.`;document.title=`${label} Finds | Roomworthy`;el.innerHTML=chosen.length?chosen.map(card).join(''):'<p>No products in this collection yet.</p>';}
function renderAll(){const el=document.getElementById('allProducts');if(el)el.innerHTML=products.map(card).join('');}
renderFeatured();renderCategory();renderAll();
})();